//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Errandscall.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDocument
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public string document_name { get; set; }
        public string document_mime { get; set; }
        public byte[] document_data { get; set; }
        public string documet_group { get; set; }
        public int document_index { get; set; }
        public System.DateTime AddedOnDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
