//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrandscallDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feed
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public byte[] Video { get; set; }
        public byte[] Image { get; set; }
        public string Message { get; set; }
        public System.DateTime AddedOnDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
