//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrandscallDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Password { get; set; }
        public int UserRoleId { get; set; }
        public string OTP { get; set; }
        public Nullable<System.DateTime> RequestDateTime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
