//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrandscallDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceMessage
    {
        public int Id { get; set; }
        public string Method { get; set; }
        public string Message { get; set; }
        public System.DateTime AddedOnDateTime { get; set; }
    }
}
